const salonTypes = {
  GET_SALON: "@salon/GET",
  UPDATE_SALON: "@salon/UPDATE",
  ALL_SERVICES_SALON: "@salon/ALL_SERVICES",
  UPDATE_SERVICES_SALON: "@salon/UPDATE_SERVICES",
  UPDATE_FORM_SALON: "@salon/UPDATE_FORM",
  UPDATE_SCHEDULING_SALON: "@salon/UPDATE_SCHEDULING",
  FILTER_SCHEDULE_SALON: "@salon/FILTER_SCHEDULE",
  UPDATE_SCHEDULE_SALON: "@salon/UPDATE_SCHEDULE",
};

export default salonTypes;
